### ISSUE TITLE
Server crash with Integrated Circuit and Comparator

### ISSUE THREAD

**Issue by Xiaminou** [Victorious3/Integrated-Circuits#112] opened 2015-06-11 12:06 UTC
![2015-06-11_14 02 26](https://cloud.githubusercontent.com/assets/8670392/8106554/84cb5e72-1042-11e5-8ce6-24b8aab251a8.png)
This setup works, however while building it I had to rotate the Comparator into place first, otherwise if I had the comparator "in" facing the Integrated Circuit it would crash the server.

pastebin: http://pastebin.com/fasZDkpz

**Comment by evg-zhabotinsky** [comment] 2015-06-11 13:14
It is 0.8 version, by the way.

I reproduced the crash in single player mode.
It crashes when you place circuit *after (not before!)* comparator and its `in` side is facing the circuit.

Could not reproduce it in 0.9 though.
Maybe because now you place a passive socket first, and only then solder circuit onto it.

**Comment by evg-zhabotinsky** [comment] 2015-06-11 13:35
Looks like I know why it happens.

`ItemPartGate.place(...)` first places block in the world, then queries its tileentity, and only then sets `gate` field of this tileentity to an actual gate.
Meanwhile, placing a block causes a block update, someone comes asking for redstone output from the gate, and it crashes because of assumption that `gate` field is valid.

Said that, I don't think it can happen in 0.9, because of new socket system.

**I might be wrong anywhere above**

**Comment by Victorious3** [comment] 2015-06-11 13:51
If you experience the same with 0.9, tell me, otherwise closing.

**Closed by Victorious3** 2015-06-11 13:51 UTC
