### ISSUE TITLE
Wired weirdness.

### ISSUE THREAD

**Issue by evg-zhabotinsky** [Victorious3/Integrated-Circuits#109] opened 2015-06-10 09:27 UTC
Screenshots from 0.8, but also tested on 0.9 -- glitches are the same.

Minimal example:
![screenshot from 2015-06-10 11 56 42](https://cloud.githubusercontent.com/assets/6692701/8078668/fef2e138-0f67-11e5-840c-08a94a1906b5.png)![screenshot from 2015-06-10 11 56 50](https://cloud.githubusercontent.com/assets/6692701/8078673/0182a2c6-0f68-11e5-953e-99759f314ca8.png)
![screenshot from 2015-06-10 11 57 13](https://cloud.githubusercontent.com/assets/6692701/8078679/07adab46-0f68-11e5-81a6-6057615fb47b.png)![screenshot from 2015-06-10 11 57 18](https://cloud.githubusercontent.com/assets/6692701/8078693/19567954-0f68-11e5-898f-8fa53d5e8fad.png)
![screenshot from 2015-06-10 11 57 22](https://cloud.githubusercontent.com/assets/6692701/8078699/1d7acfd0-0f68-11e5-9c15-1b453cbc7068.png)
Basically, you create loop, power it with torches, remove torches in the same order as you placed them and the loop ends up powering itself.
Vanilla redstone, ProjectRed and most others use signal strength to counter such issues.
Others, like MFR, might treat network of connected wires as a whole and directly combine all signals on it.

Different example of weirdness:
![screenshot from 2015-06-10 12 10 36](https://cloud.githubusercontent.com/assets/6692701/8078975/2d63230a-0f6a-11e5-8d4c-1b4b6c606234.png)![screenshot from 2015-06-10 12 10 49](https://cloud.githubusercontent.com/assets/6692701/8078983/3c72ba86-0f6a-11e5-8401-108d031e02de.png)
![screenshot from 2015-06-10 12 15 06](https://cloud.githubusercontent.com/assets/6692701/8079067/e501f342-0f6a-11e5-91c5-16e15d175e9a.png)![screenshot from 2015-06-10 12 19 17](https://cloud.githubusercontent.com/assets/6692701/8079072/ec7a9750-0f6a-11e5-9a9a-79363ca649c6.png)
So, you just change pin configuration of some gate and end up with glitched wire.
Especially annoying in huge complex circuits.

**Comment by Victorious3** [comment] 2015-06-10 12:15
I noticed the wires glitching sometimes, the problem is that I don't know how much of that is related to desyncs which are only happening on the client side, and how much of it is "real" and could interfere with the finished circuits operating properly.
I'll have a look at it again, thanks for telling me.

**Comment by evg-zhabotinsky** [comment] 2015-06-10 12:54
The glitches I described only happen when editing IC, but they are carried through into finished ICs if left alone.

What do you mean by saying "desyncs"?
It sounds to me like packet loss and other random behaviors.
I did the above examples in singleplayer, really slowly, and they are reliably reproducible.

**Comment by Victorious3** [comment] 2015-06-10 12:58
@evg-zhabotinsky The CAD logic is mostly running server side, if it forgets to inform the client of the changes, wires will glitch out.

**Comment by evg-zhabotinsky** [comment] 2015-06-14 05:21
Yet another one, and this time it is **not** caused by editing!
![screenshot from 2015-06-14 08 10 20](https://cloud.githubusercontent.com/assets/6692701/8147330/87976b1e-126d-11e5-95c8-8e08bbdf6159.png)
![screenshot from 2015-06-14 08 10 24](https://cloud.githubusercontent.com/assets/6692701/8147331/89e3ded4-126d-11e5-9113-0fe3859fc39f.png)
![screenshot from 2015-06-14 08 10 32](https://cloud.githubusercontent.com/assets/6692701/8147332/8bef779c-126d-11e5-9ab2-052ff6c7ba08.png)
These AND gates should keep themselves on, as long as signal from left IC side is high.
The left one, however, refuses to do so.
Also, turning PCB 90 degrees clockwise "fixes" the problem!

**Comment by Victorious3** [comment] 2015-06-14 07:53
@evg-zhabotinsky Try to revert at the point before your changes. Gates malfunctioning from different sides can only mean that something with the delay is broken.

**Comment by evg-zhabotinsky** [comment] 2015-06-14 21:08
@Victorious3 0.8 is all the same so I guess it cannot be my fault :-)
Something with instantaneous (within 1 tick) signal propagation seems to be broken (at least in the last example).

**Comment by evg-zhabotinsky** [comment] 2015-06-14 21:44
Other affected configurations (now with buffers instead of AND):
![screenshot from 2015-06-15 00 22 14](https://cloud.githubusercontent.com/assets/6692701/8150485/ad5b1440-12f4-11e5-829e-6df357985bc5.png)![screenshot from 2015-06-15 00 43 34](https://cloud.githubusercontent.com/assets/6692701/8150575/92ac25c8-12f7-11e5-9e89-3170b903ba42.png)

While this works (as does connecting "external power" to any loop point other than right before buffer):
![screenshot from 2015-06-15 00 28 28](https://cloud.githubusercontent.com/assets/6692701/8150509/734dd124-12f5-11e5-9088-9b034946ed8b.png)![screenshot from 2015-06-15 00 29 24](https://cloud.githubusercontent.com/assets/6692701/8150515/96be283e-12f5-11e5-89c0-934f6846ed2e.png)

As seen from these examples, **"North"** direction seems to be special.

**Comment by evg-zhabotinsky** [comment] 2015-06-14 22:02
Looks like the last commit has fixed all of the above "not editor related" problems!

But e.g. changing NOT gate outputs is still broken.

**Comment by Victorious3** [comment] 2015-06-14 22:36
@evg-zhabotinsky I'll close this because I can't tell which of those still apply and which not. Please create a new issue with those that persist.

**Closed by Victorious3** 2015-06-14 22:36 UTC
Labels: bug
